### ISSUE TITLE
rvm: command not found

### ISSUE THREAD

**Issue by lulalalalistia** [listia/laptop#3]
Prior to bootstrapping, I have only rbenv but not rvm.
During https://github.com/listia/listia/wiki/Development-Environment-Setup#auto-bootstrap , it stopped like this:

```
Installing rvm, to change Ruby versions ...
Found an rvm
...
Installing Ruby ruby-1.9.3-p547 ...
/dev/fd/63: line 284: rvm: command not found
/dev/fd/63: line 287: rvm: command not found
failed
```

**Comment by jamesfong** [comment]
Just got this too doing a new setup

```
Installing Ruby ruby-2.0.0-p645 ...
/dev/fd/63: line 284: rvm: command not found
/dev/fd/63: line 287: rvm: command not found
failed
```

**Comment by kureikain** [comment]
Finally find out the issues, the way I detect `rvm installation` is not reliable. Fixed in: https://github.com/listia/laptop/commit/fb0798007ebec6cff378f6db3b8c0e43c3ed4e71
